theme: jekyll-theme-cayman
title: "Privacy Policy"
description: "WiFi Admin Page App - Privacy Policy"
github:
  is_project_page: false
  
<script src="http://code.jquery.com/jquery-1.4.2.min.js"></script> <script> var x = document.getElementsByClassName("site-footer-credits"); setTimeout(() => { x[0].remove(); }, 10); </script>
